### ISSUE TITLE
What is the source of truth?

### ISSUE THREAD

**Issue by Michael-Rea** [himynameisdave/isbobbarkerstillalive#6]
I stumbled onto your website and thought it was a really amusing idea. Reading through the code, it looks like come-on-down.svelte gets a response from https://c5q496vt22.execute-api.us-east-1.amazonaws.com/dev/isbobbarkerstillalive to infer whether he's alive or not. Quick question: how does THAT server infer whether he's alive? Is it parsing Wikipedia for a death date, or is this just manually flipped on the server side?

**Comment by himynameisdave** [comment]
Hello! Sorry I haven't answered this, it somehow go buried under other issues from other projects!

So that's a lambda/serverless function which is doing basically exactly as you mentioned, it's grepping the first sentence of [Bob's wikipedia page](https://en.wikipedia.org/wiki/Bob_Barker) for the word `'is'` or `'was'` and returns `true` if we find `'was'`. I have no idea where the source for that lambda is, or why it isn't included in this repo in the first place, but I will look for it and try to add it here (even though it is extremely simple).
